import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Provider from "@/context/Provider";
import '@fontsource-variable/inter';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter w-full h-full min-h-screen max-w-full">
        <Provider>
          {children}
        </Provider>
        </body>
    </html>
  );
}
